project:
  type: website
  output-dir: docs

website:
  title: "educ8009-assignments"
  sidebar: 
    style: "docked"
    search: false
    contents: 
      - text: "Home"
        href: index.qmd
      - section: "Lecture Notes"
        contents: "lecture-notes.ipynb"
      - section: "Labs"
        contents: 
          - auto: "session*/assignment*"

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



