project:
  type: website
  output-dir: docs

website:
  title: "educ8009-assignments"
  sidebar: 
    style: "docked"
    search: false
    contents: 
      - text: "Home"
        href: index.qmd
      - section: "Coursework"
        contents: 
          - auto: "*.ipynb"
          - auto: "*.qmd"
      - section: ""

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



