---
title: "Currently I haven't got any idea"
subtitle: "A short term paper for EDUC8009"
author: "Yang SHEN, Y-C4-7113-4"
format: 
    pdf: 
        documentclass: article
---

The journey of discovering the open data starts here. 

# Introduction
Brief introduction, maybe like the of each lab works. 

# Research question

Briefly describe the background and the research questions. Comprehensive literature review is required for journal papers but not required for this project.

# Data and methods
Describe the source of the data and all data cleaning steps (how many observations are removed due to missing values, whether a subset rather than the whole dataset is used for analysis, etc.) to make sure that this study is replicable by readers of the paper. Basic descriptive statistics, including relevant tables and/or plots, should be provided. Relate your research question to which methods to use.

# Results
Show and interpret your findings from the data. Only report necessary statistical results. It is unacceptable to simply paste a screenshot of tables obtained from statistical software which include a lot of irrelevant information. Tables and Figures should be numbered and have captions that describe what they show.

# Conclusion and discussion
Summarize the paper. Discuss limitations of the current study (whether the statistical method used is appropriate, whether the relationship is correlation rather than causation, whether the data is collected from a nonrepresentative sample, etc.) and propose possible future directions.